export const SET_DATA_ARRAY = 'SET_DATA_ARRAY';
export const CHANGE_SORT_ORDER = 'SET_SORT_ORDER';
export const CHANGE_CURRENT_SORT_FIELD = 'SET_CURRENT_SORT_FIELD';
export const CHANGE_FILTERED = 'CHANGE_FILTERED';
export const CHANGE_FILTER_INPUT = 'CHANGE_FILTER_INPUT';
export const CHANGE_PAGE_NUMBER = 'CHANGE_PAGE_NUMBER';
export const SET_CHOSEN_ROW = 'SET_CHOSEN_ROW';
export const CHANGE_FILTERED_AND_SORTED = 'CHANGE_FILTERED_AND_SORTED';